### ISSUE TITLE
Client crash after launching game

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#21]
https://forums.cncnet.org/index.php?topic=6962.0;topicseen

7.12. 18:25:37.576    Writing spawn.ini
07.12. 18:25:37.610    Writing RA2 Mode Setting
07.12. 18:25:37.629    Writing map.
07.12. 18:25:37.636    Loading map INI from C:\Program Files (x86)\Red Alert 2\Maps\Yuri's Revenge\XMP19T4.map
07.12. 18:25:37.749    Writing settings INI.
07.12. 18:25:37.796    KABOOOOOOM!!! Info:
07.12. 18:25:37.805    Message: Exception has been thrown by the target of an invocation.
07.12. 18:25:37.815    Source: mscorlib
07.12. 18:25:37.821    TargetSite.Name: InvokeMethod
07.12. 18:25:37.827    Stacktrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Rampastring.XNAUI.XNAControls.Callback.Invoke()
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ‏⁭‬⁪⁪‍‭‪⁬‎‫⁯⁪⁭‬‎‎‮⁮⁮‌‫‌⁮⁮⁮‪‬‏⁮⁫​‎‪‭‏‎⁯‎‬‮.‫‪‭‭‏‪​‭⁯‍⁪‭‌‍⁪‬​‌‎‮⁪⁭‭⁮​‌‍‍‭‫‬⁯‬⁭‭⁭‪‬‌⁯‮()
   at ⁬‪‪⁬⁭⁫⁪‎⁬⁯⁪⁭⁭‮‮‮⁪‮‌‬‬​‏‫‪⁪​‭⁫⁮⁫‎‌⁪‮‮‍‍⁫‏‮.‎⁪‪⁫‬‭‮⁯⁬⁪⁪⁪‎‬‏⁮‪‮‪‮‏‏‮⁯‌‪‮‎‎‮‪‮⁯​‮⁫⁪⁮⁪‫‮(String[] )
   at ⁬⁬⁮⁭‮‍‭‍⁯‏‎⁫‎‮⁯⁪‬​⁯‏‭‮⁪‪‭​‭⁭⁬‌‎‬‭‌​‬⁮‫‌⁯‮.‮‏‏⁭⁬⁯⁪‎​‏⁬⁬⁬‭⁮‬‭‭‎‌⁮‍⁭⁯⁯⁫⁪‫​‭⁬⁫‪‏⁫‎‌⁪⁪⁯‮(String[] )
07.12. 18:25:37.833    InnerException info:
07.12. 18:25:37.840    Message: Access to the path 'C:\Program Files (x86)\Red Alert 2\EXCEPT.TXT' is denied.
07.12. 18:25:37.847    Stacktrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at ‬‏‭⁪‮‌‏‌‌‪‪‍⁪‬‌‏‮⁬⁯‌⁪⁭‮‪⁬⁭‏⁭‭‪⁪‎‌‭‎⁭⁯‌‭⁭‮.⁮‮⁪​‌​‫⁫‌⁬‎​‌⁫⁭‎‌​‪‭⁭‮‏‌‎⁭⁯‮‏⁭‌‬‭⁪⁭⁮⁪‫‫⁪‮()
   at System.Action.Invoke()
   at ClientGUI.GameProcessLogic.StartGameProcess(Int32 processId)
   at ‭‮​‭‍⁭‬‮‬⁯‌‭⁫​‏⁪‬‌⁭⁮‬‮⁯​‏‬‪⁯‭​‫⁫‪‭⁬‎​‪‫⁯‮.⁮‎‪‬⁯‬⁫​⁯‏‬⁯⁪⁮‍‏‎‌‍​‍‏‌‪‫‪‪⁭⁮‮‪‍‍⁫‫⁯‪‭‌⁯‮()
   at ‎‫‌‏⁭‌⁫‪‍‏⁭⁮‫‮‭⁪⁭‪‎⁯‏‏‏‭‮⁪⁬⁬⁭‮⁯‪⁪‏‎‬⁪‭⁪⁫‮.⁫⁬‍⁬⁪​‎‎‮⁮⁪​‭‭⁭‎⁭‭‍‏⁫⁯‍‏​‏‬⁯‎​​‎‭⁭‭⁯⁮‬‪‬‮(String , String )
   at ​‍‫‎‎‏⁭⁪‪‭‌⁮‪⁭‭⁫‏⁯‌‭⁫​⁫‪⁭‭⁫‍‏‏‭⁬⁯‮⁮‍⁮​⁯⁪‮.⁬⁬‫⁯​‫⁬​‎‌‬‪‎‍⁫‏‪⁮‌⁫‬⁭‫​‮⁪⁭​⁯‭‪⁮⁭‌‭‪⁮‬​‪‮(String , String )
   at ‎‫‌‏⁭‌⁫‪‍‏⁭⁮‫‮‭⁪⁭‪‎⁯‏‏‏‭‮⁪⁬⁬⁭‮⁯‪⁪‏‎‬⁪‭⁪⁫‮.‭‏⁮⁪⁭⁭‬‌‮​‫⁫‍‍‫⁭‪⁫‍‬⁭⁯‌⁭‫‫⁯‍⁫‌‮‍⁪⁪⁫‎‪⁭‬⁯‮(Object , ‫‌‍⁬⁫‮‫‏‭‎‭⁯‮‬⁬​⁫⁬‭⁯‮‭‪‍⁯‫‫‭⁯‌⁫‭‪⁯​⁯‏‍‫‮‮ )
   at ‬⁯⁯⁯​‮​‬‏​‫⁭⁭‏⁭⁭‪⁪‭‎⁪‏‪‍‍‮‮‌​⁪⁮‬‎⁭‬⁯⁫⁫‫⁭‮.‪‍⁭⁮⁪‎‬⁬‫⁭⁮⁯‎‬​⁬‮⁫‮​​⁮​‪⁯‫⁪⁯‭‬⁭⁯‏⁮⁬⁫‏⁫‍⁭‮(String , String )
   at ⁯‎‭⁮‏‍⁭‍⁭‍‬⁭‍⁮‫‌‎‮‍‎⁯‭‍‎⁯‍‪⁪‎‎⁯⁮‏‏‪‏‍‫⁯‌‮.‌‎‏‪‎‫‬⁬‬‎‭‮‬‎⁫‍⁬‪‬‭‮⁪‬‏⁯⁫⁭‪⁯⁯⁪⁫‎⁬​⁭‫‏⁭‮(String , String , String )
07.12. 18:25:38.955    Message received: :CaptainN!~4--yG9mKQ@gamesurge-2d067b2c.hsd1.mi.comcast.net NOTICE #cncnet-yr-games :GAME R3;3.0.41;4;#cncnet-yr-game6321982;CaptainN's Game;11000;CaptainN,TheDave;[4] Frostbite;Battle;104.156.251.89;0

07.12. 18:25:38.961    RMP: CaptainN!~4--yG9mKQ@gamesurge-2d067b2c.hsd1.mi.comcast.net NOTICE #cncnet-yr-games,GAME R3;3.0.41;4;#cncnet-yr-game6321982;CaptainN's Game;11000;CaptainN,TheDave;[4] Frostbite;Battle;104.156.251.89;0,
07.12. 18:25:39.128    SRM: AWAY :In-game
07.12. 18:26:07.566    SRM: PING LAG598197
07.12. 18:26:37.566    SRM: PING LAG381681
07.12. 18:27:07.567    SRM: PING LAG165164
07.12. 18:27:37.568    SRM: PING LAG848646

**Comment by Rampastring** [comment]
Fixed in https://github.com/CnCNet/xna-cncnet-client/commit/75c6d4eb42cfa49acfbd15c0d6ece95db35c439d
