### ISSUE TITLE
HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#27]
https://forums.cncnet.org/index.php?topic=7038.0

14.12. 23:12:40.984    Checking if custom components are outdated.
14.12. 23:13:12.498    KABOOOOOOM!!! Info:
14.12. 23:13:12.500    Message: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown
14.12. 23:13:12.508    Source: SharpDX
14.12. 23:13:12.510    TargetSite.Name: CheckError
14.12. 23:13:12.515    Stacktrace:    at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   at SharpDX.Direct3D11.ShaderResourceView..ctor(Device device, Resource resource)
   at Microsoft.Xna.Framework.Graphics.Texture.GetShaderResourceView()
   at Microsoft.Xna.Framework.Graphics.TextureCollection.PlatformSetTextures(GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.TextureCollection.SetTextures(GraphicsDevice device)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.ApplyState(Boolean applyShaders)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformDrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives[T](PrimitiveType primitiveType, T[] vertexData, Int32 vertexOffset, Int32 numVertices, Int16[] indexData, Int32 indexOffset, Int32 primitiveCount, VertexDeclaration vertexDeclaration)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.FlushVertexArray(Int32 start, Int32 end, Effect effect, Texture texture)
   at Microsoft.Xna.Framework.Graphics.SpriteBatcher.DrawBatch(SpriteSortMode sortMode, Effect effect)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at Rampastring.XNAUI.WindowManager.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_0(IDrawable drawable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ‎⁭⁬⁭‌‍‭⁭⁫‭‏‏​⁭⁬‪‎⁬‭‎‍‍‍⁯⁫⁬‮‌⁯‍‪⁯⁬⁫‮‎‏⁯⁫‏‮.‌‪‎⁯⁯‪​​‭‮‭‎⁫‍‌‌​‏‪‏‮‮⁫⁯‪‎⁮‏‎⁪‮​‭‎‮⁪‍‬‮⁬‮()
   at ⁫‪⁮⁫‫⁫⁪⁫⁫‏‭‫‬‮‍⁯⁪⁬‬⁪‏‏‬‬​‭⁬⁮​‍‪⁬⁮‏‭⁮‪‍‎‬‮.‏⁪⁮⁬⁬‭‮‬⁫‌‭‌‮‬⁯‭‪⁬‎‏‬​⁪⁮‏‬‪‪‭‪⁫‫​⁮‭⁬⁭⁮‍‪‮(String[] )
   at ⁫⁬‪⁪‍‍‭⁪‭⁯‌​‮‮‏⁬‬‪‮‮⁫⁭‮‏⁭‍‏⁫‬⁭⁭‭‬⁯‌​‮‫‮⁬‮.⁮‏⁯⁪‬⁯⁪⁫‬⁯⁮‬‫‭‪‌‭⁭‪⁬⁭‫⁮⁮⁪‮‫​⁫‏‍‏⁪⁪⁪‏‫⁪‍⁬‮(String[] )

**Comment by Rampastring** [comment]
https://msdn.microsoft.com/fi-fi/library/windows/desktop/bb509553(v=vs.85).aspx

DXGI_ERROR_DEVICE_REMOVED: The video card has been physically removed from the system, or a driver upgrade for the video card has occurred.

Sounds like a potential graphics card / driver issue?

**Comment by GrantBartlett** [comment]
Repairing .NET framework, updating video drivers apparently solved this.

**Comment by GrantBartlett** [comment]
@Rampastring getting 2-3 reports of this error when people applied the latest update. 
https://forums.cncnet.org/index.php?topic=6930.msg51758#msg51758
https://forums.cncnet.org/index.php?topic=7255.0

**Comment by Rampastring** [comment]
I can only give the same advice as before. The two linked crashes happened in completely different operations that aren't related to each other in any way.
