### ISSUE TITLE
Client crashed after upgrading to 8.8.1

### ISSUE THREAD

**Issue by zhengshuang2005** [CnCNet/xna-cncnet-client#276]
![image](https://user-images.githubusercontent.com/37681001/146692375-0e4c4f1a-db18-4a06-97a8-c8be84e2684d.png)

**Comment by zhengshuang2005** [comment]
19.12. 16:01:18.415    ***Logfile for Yuri's Revenge client***
19.12. 16:01:18.415    Client version: 2.6.10.1
19.12. 16:01:18.415    Loading settings.
19.12. 16:01:18.430    Initializing updater.
19.12. 16:01:18.430    Operating system: Microsoft Windows NT 6.2.9200.0
19.12. 16:01:18.430    Selected OS profile: WIN810
19.12. 16:01:18.430    Attempting to delete temporary updater directory.
19.12. 16:01:18.493    Removing partial custom component downloads.
19.12. 16:01:18.493    Checking for the existence of FinalSun.ini.
19.12. 16:01:18.493    FinalSun.ini doesn't exist - writing default settings.
19.12. 16:01:18.493    An exception occured while checking the existence of FinalSun settings
19.12. 16:01:18.493    Writing installation path to the Windows registry.
19.12. 16:01:18.924    Initializing GameClass.
19.12. 16:01:19.076    KABOOOOOOM!!! Info:
19.12. 16:01:19.076    Message: Method not found: 'Void ClientGUI.XNAWindow..ctor(Rampastring.XNAUI.WindowManager)'.
19.12. 16:01:19.076    Source: DTAClient
19.12. 16:01:19.076    TargetSite.Name: .ctor
19.12. 16:01:19.079    Stacktrace:    at DTAClient.DXGUI.Generic.LoadingScreen..ctor(WindowManager windowManager)
   at DTAClient.DXGUI.GameClass.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)

**Comment by zhengshuang2005** [comment]
Thanks for the help!

**Comment by zhengshuang2005** [comment]
Sorry posted in the wrong place.
