### ISSUE TITLE
Wine/Mono support

### ISSUE THREAD

**Issue by elegantandrogyne** [CnCNet/xna-cncnet-client#29]
I'm having a hard time trying to get the client to run under Wine on a Linux machine; tested Mental Omega, DTA and TI - with the same result.

Using Debian stretch/sid amd64, but probably any Wine setup is affected (MacOS as well).
Wine is 1.8.5 or 2.0rc1 (wine-development), Mono is 4.6.1.3 (complete with all libraries)

1. create a clean 32-bit wineprefix:
`env WINEARCH=win32 WINEPREFIX=/home/user/cnc` winecfg
2. change settings: windows version = win7; prefer native for ddraw.dll and wsock32.dll
3a) unzip TI or DTA to subdirectories of /home/user/cnc/drive_c/
3b) install Origin and RA2+YR, then unzip MO to the game's directory
4. in terminal: cd to the game's directory, then enter:
`env WINEPREFIX=/home/user/cnc {wine, wine-development} {TI_Launcher.exe, DTA.exe, MentalOmegaClient.exe}'

I should see a client, but it goes KABOOOOOOM!; error code 0x800040001 not implemented

client log (for TI):

19.12. 20:29:16.206    ***Logfile for Twisted Insurrection client***
19.12. 20:29:16.314    Client version: 2.0.0.5
19.12. 20:29:16.314    Loading settings.
19.12. 20:29:16.507    Initializing updater.
19.12. 20:29:16.510    Update mirror count: 1
19.12. 20:29:16.510    Running from: clientdx.exe
19.12. 20:29:16.513    Operating system: Microsoft Windows NT 6.1.7601.65536 Service Pack 1
19.12. 20:29:16.513    Selected OS profile: Windows 7
19.12. 20:29:16.516    Removing partial custom component downloads.
19.12. 20:29:16.518    Checking for the existence of FinalSun.ini.
19.12. 20:29:16.518    FinalSun settings file exists.
19.12. 20:29:16.534    Writing installation path to the Windows registry.
19.12. 20:29:16.550    Checking system specifications failed. Message: The method or operation is not implemented.
19.12. 20:29:17.874    KABOOOOOOM!!! Info:
19.12. 20:29:17.874    Message: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Unknown
19.12. 20:29:17.876    Source: SharpDX
19.12. 20:29:17.876    TargetSite.Name: CheckError
19.12. 20:29:17.882    Stacktrace:   at SharpDX.Result.CheckError () <0x1ddc0e0 + 0x0004f> in <filename unknown>:0 
  at SharpDX.DXGI.Device1.SetMaximumFrameLatency (Int32 maxLatency) <0x1dfad28 + 0x00043> in <filename unknown>:0 
  at SharpDX.DXGI.Device1.set_MaximumFrameLatency (Int32 value) <0x1dfad00 + 0x00017> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources (Boolean useFullscreenParameter) <0x1df9568 + 0x00907> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformInitialize () <0x1df47c8 + 0x00023> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize () <0x1df45d0 + 0x00013> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor (Microsoft.Xna.Framework.Graphics.GraphicsAdapter adapter, GraphicsProfile graphicsProfile, Microsoft.Xna.Framework.Graphics.PresentationParameters presentationParameters) <0x1df0720 + 0x00337> in <filename unknown>:0 
  at Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize () <0x1df0128 + 0x001e3> in <filename unknown>:0 
  at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice () <0x1df00e0 + 0x00013> in <filename unknown>:0 
  at Microsoft.Xna.Framework.GamePlatform.BeforeInitialize () <0x1deffc8 + 0x000e1> in <filename unknown>:0 
  at MonoGame.Framework.WinFormsGamePlatform.BeforeInitialize () <0x1ddee38 + 0x00063> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Game.DoInitialize () <0x1ddecd0 + 0x0001e> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Game.Run (GameRunBehavior runBehavior) <0x1ddd648 + 0x0007b> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Game.Run () <0x1ddd5f0 + 0x00027> in <filename unknown>:0 
  at DTAClient.Startup.Execute () <0x1da8e28 + 0x00347> in <filename unknown>:0 
  at DTAClient.RealMain.ProxyMain (System.String[] args) <0x1d87f40 + 0x00437> in <filename unknown>:0 
  at DTAClient.Program.Main (System.String[] args) <0x1d60f78 + 0x00247> in <filename unknown>:0

**Comment by Rampastring** [comment]
Be aware that I only have a Windows 10 so I can't "officially" support running the client under Linux.

Based on the error it looks like you're missing DirectX11. The Windows XP version of the client uses DX9 and so it might be easier to run; try changing the Windows version to Windows XP, install XNA Framework 4.0 Refresh ( https://www.microsoft.com/en-us/download/details.aspx?id=27598 ) And then try to run Resources\clientxna.exe.

**Comment by elegantandrogyne** [comment]
Re-tested in a fresh 32-bit WinXP wineprefix:
1. `env WINEARCH=win32 WINEPREFIX=/home/user/CNC winecfg`
2. override ddraw and wsock32, like before
3. `env WINEPREFIX=/home/user/CNC winetricks xna40` (installs MS .NET 4.0 and XNA)
4. `cd /home/user/CNC/drive_c/TI'
5. 'env WINEPREFIX=/home/user/CNC wine Resources/clientxna.exe'

19.12. 21:17:19.555    ***Logfile for Twisted Insurrection client***
19.12. 21:17:19.771    Client version: 2.0.0.5
19.12. 21:17:19.771    Loading settings.
19.12. 21:17:20.228    Initializing updater.
19.12. 21:17:20.235    Update mirror count: 1
19.12. 21:17:20.235    Running from: clientxna.exe
19.12. 21:17:20.240    Operating system: Microsoft Windows NT 5.1.2600 Service Pack 3
19.12. 21:17:20.240    Selected OS profile: Windows XP
19.12. 21:17:20.280    Removing partial custom component downloads.
19.12. 21:17:20.282    Checking for the existence of FinalSun.ini.
19.12. 21:17:20.282    FinalSun settings file exists.
19.12. 21:17:20.309    Writing installation path to the Windows registry.
19.12. 21:17:21.174    Hardware info: Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz (1 cores) Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz (1 cores)  Video controller: Mobile Intel(R) GM45 Express Chipset Family 
19.12. 21:17:22.226    InitGraphicsMode: 1920x1200
19.12. 21:17:23.114    Loading maps.
19.12. 21:17:23.150    Checking local file versions.
19.12. 21:17:25.874    Attempting to parse INI\Battle.ini to populate mission list.
19.12. 21:17:25.922    Finished parsing INI\Battle.ini.
19.12. 21:17:25.924    Attempting to parse INI\BattleE.ini to populate mission list.
19.12. 21:17:25.925    File INI\BattleE.ini not found. Ignoring.
19.12. 21:17:26.284    Skipping reading statistics because the file doesn't exist!
19.12. 21:17:26.728    {X:12 Y:712 Width:390 Height:21}
19.12. 21:17:27.144    {X:12 Y:712 Width:390 Height:21}
19.12. 21:17:27.668    {X:12 Y:712 Width:390 Height:21}
19.12. 21:17:28.150    Loading friend list failed!
19.12. 21:17:28.275    KABOOOOOOM!!! Info:
19.12. 21:17:28.277    Message: Song playback failed. Please verify that the song is not DRM protected. DRM protected songs are not supported for creator games.
19.12. 21:17:28.300    Source: Microsoft.Xna.Framework
19.12. 21:17:28.302    TargetSite.Name: Play
19.12. 21:17:28.310    Stacktrace:    at Microsoft.Xna.Framework.Media.MediaQueue.Play(Song song)
   at DTAClient.DXGUI.Generic.MainMenu.PlayMusic()
   at DTAClient.DXGUI.Generic.MainMenu.PostInit()
   at DTAClient.DXGUI.Generic.LoadingScreen.Finish()
   at DTAClient.DXGUI.Generic.LoadingScreen.Start()
   at DTAClient.DXGUI.Generic.LoadingScreen.Update(GameTime gameTime)
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at DTAClient.Startup.Execute()
   at DTAClient.RealMain.ProxyMain(String[] args)
   at DTAClient.Program.Main(String[] args)
19.12. 21:17:28.310    InnerException info:
19.12. 21:17:28.310    Message: An unexpected error has occurred.
19.12. 21:17:28.310    Stacktrace: 

After applying a workaround from https://forums.cncnet.org/index.php?topic=6980.0 (moved mainmenu.wma -> mainmenu.wma-old and mainmenu.xnb -> mainmenu.xnb-old) the client started working, so I may even be able to play the game after all :)

**Comment by Rampastring** [comment]
With the fix for #30, Wine should be able to run the XNA build of the client without the user having to delete / rename any files.

**Comment by guilhermesgb** [comment]
Thank you for this thread! It actually helped me manage to get Mental Omega working on my setup (using Wine 2.0.3, Windows XP). Previously I couldn't get it to work at all.

I think three things pointed here made the difference:

1. Setting the library overrides (to prefer native instead of the other option);
2. Removing a few .wav and .xnb files (via trial and error I discovered we must *remove all .wav* files in the `Resources` and `Resources/MainMenu` folders and *remove all .xnb files except the SpriteFont ones* in the `Resources`folder;
3. Actually running `Resources/clientxna.exe` instead of `MentalOmegaClient.exe` (via wine, of course)

I had previously setup my win32 architecture and used winetricks to install `xna40` already.

Below is the original mail I ended up sending to the Mentalmeisters team, describing my original issues. Hopefully anyone with the same problems will also get the game working!

> Hello guys. First of all congrats on such a great mod. Watching YT videos got me excited to try playing this game as I have played RA and RA2 a lot (and a bit of Yuri's Revenge too which I disliked) back in the day... Second of all, sorry for my eventual English mistakes as it is not my first language.
> So, a bit of story: I boot up a Windows XP (SP3) virtual machine, installed RA2 and Yuri's Revenge (1.001), and they both ran just fine, I could actually play a few campaign missions to sort of get up to speed again.
>
> Then it was time to actually test Mental Omega. I proceeded as instructed on the getting started page, copying all seven required files (a few .mix, a couple .dll and the game executable) into a new folder, where I then unzipped Mental Omega 3.3 and the Soundtrack.
>
> Unfortunately, when I ran the Mental Omega client, I got this very odd 0xc0000135 error which absolutely gave me no clues on what was the issue there.
>
> Fortunately, though, after a long time I figured out that XNA 4.0 (and thus .NET Framework 4) were required to run the client (or one of its dependencies) and thus I got into installing these libraries (- If I recall correctly, running the game on WINE was what helped me figure out that that was the underlying issue as there I didn't get this odd error but a warning that XNA 4.0 was required to run the client).
>
> But now I'm stuck in a new problem...
>
> Running the client again, I got another error, which opens a popup window titled "MentalOmegaClient.exe - .NET Framework Initialization Error", embedding the following message "Unable to find a version of the runtime to run this application".
>
> I've attempted using other versions of XNA and .NET Framework, to which the client executable then proceeded to inform me that .NET Framework 4 and XNA 4.0 are indeed the expected versions so I'm now at a loss here, unable to figure out a way to make this work.
>
> I also tried running on Wine on my host machine (by transfering all game files via a shared folder) and using winetricks to install these aforementioned dependencies... then I also got this exact same issue again.
>
> The following link shows an image of what I'm describing: https://imgur.com/a/Wx95K.
