### ISSUE TITLE
Add check for Microsoft.Xna.Framework.Media.MediaQueue.Play

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#30]
https://forums.cncnet.org/index.php?topic=7061.0

Log below. Also might kill two birds with one stone in reference to https://github.com/CnCNet/xna-cncnet-client/issues/29 and https://github.com/CnCNet/xna-cncnet-client/issues/26

20.12. 01:39:43.328    ***Logfile for Yuri's Revenge client***
20.12. 01:39:43.343    Client version: 2.0.3.1
20.12. 01:39:43.343    Loading settings.
20.12. 01:39:43.406    Initializing updater.
20.12. 01:39:43.421    Update mirror count: 1
20.12. 01:39:43.421    Running from: clientxna.exe
20.12. 01:39:43.421    Operating system: Microsoft Windows NT 5.1.2600 Service Pack 3
20.12. 01:39:43.421    Selected OS profile: Windows XP
20.12. 01:39:43.437    Removing partial custom component downloads.
20.12. 01:39:43.437    Checking for the existence of FinalSun.ini.
20.12. 01:39:43.437    FinalSun.ini doesn't exist - writing default settings.
20.12. 01:39:43.437    An exception occured while checking the existence of FinalSun settings
20.12. 01:39:43.453    Writing installation path to the Windows registry.
20.12. 01:39:44.593    InitGraphicsMode: 1600x900
20.12. 01:39:44.937    Loading maps.
20.12. 01:39:45.109    Checking local file versions.
20.12. 01:39:45.906    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.921    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.921    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.953    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.953    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.984    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:45.984    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:46.000    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:46.031    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:46.046    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:46.062    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
20.12. 01:39:46.140    Hardware info:               Intel(R) Celeron(R) D CPU 3.06GHz (1 cores)  Video controller: NVIDIA GeForce 7300 GT 
20.12. 01:39:46.687    Attempting to parse INI\Battle.ini to populate mission list.
20.12. 01:39:46.687    File INI\Battle.ini not found. Ignoring.
20.12. 01:39:46.687    Attempting to parse INI\BattleE.ini to populate mission list.
20.12. 01:39:46.703    File INI\BattleE.ini not found. Ignoring.
20.12. 01:39:46.781    Saved Games directory not found!
20.12. 01:39:47.109    Skipping reading statistics because the file doesn't exist!
20.12. 01:39:47.218    AssetLoader.LoadSound: Sound not found! none
20.12. 01:39:47.218    AssetLoader.LoadSound: Sound not found! none
20.12. 01:39:47.218    AssetLoader.LoadSound: Sound not found! none
20.12. 01:39:47.218    AssetLoader.LoadSound: Sound not found! none
20.12. 01:39:47.218    AssetLoader.LoadSound: Sound not found! none
20.12. 01:39:47.984    MultiplayerGameLobby: Saved games are not available!
20.12. 01:39:48.875    MultiplayerGameLobby: Saved games are not available!
20.12. 01:39:49.234    Loading friend list failed!
20.12. 01:39:49.312    KABOOOOOOM!!! Info:
20.12. 01:39:49.312    Message: Song playback failed. Please verify that the song is not DRM protected. DRM protected songs are not supported for creator games.
20.12. 01:39:49.359    Source: Microsoft.Xna.Framework
20.12. 01:39:49.359    TargetSite.Name: Play
20.12. 01:39:49.359    Stacktrace:    at Microsoft.Xna.Framework.Media.MediaQueue.Play(Song song)
   at ⁫‫‭‍‬⁭⁫⁬‫⁮⁬​‍‬⁪⁮‭‮‎​‌‎‏‌⁯⁫‏⁭‏‏⁭⁬⁭‮‌⁬⁭‌‍‎‮.⁬⁮‫⁭‮‌⁭‍‎⁮⁯⁭⁫‌‫⁮⁭‪‬‮‌⁯‌‬​‬​⁮⁯‏⁫‫‮⁯⁮‎​⁬⁪‪‮()
   at ⁫‫‭‍‬⁭⁫⁬‫⁮⁬​‍‬⁪⁮‭‮‎​‌‎‏‌⁯⁫‏⁭‏‏⁭⁬⁭‮‌⁬⁭‌‍‎‮.‬⁫⁯⁭‫​‬‭⁭‫⁭‫‬​⁪‌⁫⁬​⁭‬⁬⁫⁫‫⁫‮‫‮‏⁫⁯‏‌‫‫⁫‬‬⁭‮()
   at ‫⁮‫‌‪​⁮‏‬⁬⁯‭⁫‮⁮⁫‮⁭⁪‫‬⁯‪‍‫‬⁭‬‍‬‭‏‭‪⁬‬‮‪‬‫‮.⁬‪​⁫‫‬‫‎⁫‪‎‭⁬⁯⁮‫⁫⁬⁬‎⁬​​‫‫⁫‪⁭‪‌‫‌‬‪⁬‏⁯⁪⁭⁫‮()
   at ‫⁮‫‌‪​⁮‏‬⁬⁯‭⁫‮⁮⁫‮⁭⁪‫‬⁯‪‍‫‬⁭‬‍‬‭‏‭‪⁬‬‮‪‬‫‮.‭‎‍‍‭⁪⁭‍‫‍‮​‫⁫⁪⁬‌‏⁭⁭⁫‮⁪‮‫‍‍⁪‬‭‭‬‭‬‫‌‏⁬‬‮‮()
   at ‫⁮‫‌‪​⁮‏‬⁬⁯‭⁫‮⁮⁫‮⁭⁪‫‬⁯‪‍‫‬⁭‬‍‬‭‏‭‪⁬‬‮‪‬‫‮.‫‭⁬‬‪‌⁬‪⁭‬‪‍‬‍‬⁭‎⁯⁮⁪‫⁪⁯‬⁪‬‬⁫⁬⁭⁪‪‌⁫‏⁫⁪‮‎⁯‮(GameTime )
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at ‫‎‫⁫‎‌⁮‮‮⁯‍⁭‏‎‭‍⁭‫​⁮‫⁯‫⁯⁪‬‪‬⁫⁪‮‌‭‮⁮⁯⁫‎‪⁮‮.‏⁫‮‮⁭‫‫‏⁪⁮⁮⁪⁯⁬‪‫⁮⁮⁭‮⁭‏⁯⁯‏‭‍‍‬‍‪⁮⁬‌⁮‫⁭⁫‬‫‮()
   at ⁮⁫‏⁭‏‭⁬⁯‮‎⁮⁯‎‬‫‭‏‫⁯‬​‮‎‬‌‎​‭‏⁪‮‍⁪‫⁯‍⁪⁮⁭⁭‮.‌‏‏⁪⁮⁫⁯‎‮‫⁮‭⁭‮⁫⁯⁫‫⁫‮‎⁭⁮⁮‪⁬‮‎⁬⁭‬‭‏⁬⁯​‍‍⁬⁯‮(String[] )
   at ⁮‍⁯⁬​‌⁮⁮⁪‭‬‮⁭‬​⁫‮⁯‌‏⁯​⁭‏⁬‮‭⁭‎‪‌‫‎⁭‫⁬‫⁪‬‫‮.⁫⁪‪⁬‪⁬⁬⁯‪‭‭⁮‍‫‌‫‫‬⁭‌‮⁫⁪⁮⁫‍⁪‫⁯⁬⁮⁪⁮‭⁭‭‮‫⁬‫‮(String[] )
20.12. 01:39:49.359    InnerException info:
20.12. 01:39:49.359    Message: An unexpected error has occurred.
20.12. 01:39:49.359    Stacktrace:

**Comment by Rampastring** [comment]
@GrantBartlett Could you check if the commit referenced above resolves this?

**Comment by GrantBartlett** [comment]
@Rampastring confirmed as fixed

**Comment by 99linesofcode** [comment]
Got hit by something similar when running Red Alert Yuri's Revenge purchased and installed from Steam on the latest Proton Experimental with the error: `Message: The song contains video data!`.

[Found this issue on the forums](https://forums.cncnet.org/topic/6175-kabooom/) and the suggestion to remove the `MainMenuTheme.*` worked for me. Might still be missing a check somewhere or some files are not being overwritten/created correctly.

```
  at Microsoft.Xna.Framework.Media.Song.FromUri (System.String name, System.Uri uri) [0x00006] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at DTAClient.DXGUI.Generic.MainMenu.LoadThemeSong () [0x00070] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
  at DTAClient.DXGUI.Generic.MainMenu.PostInit () [0x001e8] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
  at DTAClient.DXGUI.Generic.LoadingScreen.Finish () [0x00037] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
  at DTAClient.DXGUI.Generic.LoadingScreen.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00039] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
  at Rampastring.XNAUI.WindowManager.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00140] in <fc455ab7275c42ba8bcecc596dc74852>:0 
  at Microsoft.Xna.Framework.Game+<>c.<.cctor>b__115_1 (Microsoft.Xna.Framework.IUpdateable updateable, Microsoft.Xna.Framework.GameTime gameTime) [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game+SortingFilteringCollection`1[T].ForEachFilteredItem[TUserData] (System.Action`2[T1,T2] action, TUserData userData) [0x0007d] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game.DoUpdate (Microsoft.Xna.Framework.GameTime gameTime) [0x00019] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x00122] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at MonoGame.Framework.WinFormsGameWindow.TickOnIdle (System.Object sender, System.EventArgs e) [0x00014] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle (System.Int32 grfidlef) [0x0001a] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
  at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop (System.IntPtr dwComponentID, System.Int32 reason, System.Int32 pvLoopData) [0x00243] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x00282] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
  at System.Windows.Forms.Application+ThreadContext.RunMessageLoop (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x0001a] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Application+ThreadContext.RunMessageLoop(int,System.Windows.Forms.ApplicationContext)
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x0000d] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
  at MonoGame.Framework.WinFormsGameWindow.RunLoop () [0x00011] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at MonoGame.Framework.WinFormsGamePlatform.RunLoop () [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior runBehavior) [0x00082] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x0000c] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
  at DTAClient.Startup.Execute () [0x004f0] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
  at DTAClient.PreStartup.Initialize (DTAClient.StartupParams parameters) [0x0052d] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
```

**Comment by SadPencil** [comment]
> Got hit by something similar when running Red Alert Yuri's Revenge purchased and installed from Steam on the latest Proton Experimental with the error: `Message: The song contains video data!`.
> 
> [Found this issue on the forums](https://forums.cncnet.org/topic/6175-kabooom/) and the suggestion to remove the `MainMenuTheme.*` worked for me. Might still be missing a check somewhere or some files are not being overwritten/created correctly.
> 
> ```
>   at Microsoft.Xna.Framework.Media.Song.FromUri (System.String name, System.Uri uri) [0x00006] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at DTAClient.DXGUI.Generic.MainMenu.LoadThemeSong () [0x00070] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
>   at DTAClient.DXGUI.Generic.MainMenu.PostInit () [0x001e8] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
>   at DTAClient.DXGUI.Generic.LoadingScreen.Finish () [0x00037] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
>   at DTAClient.DXGUI.Generic.LoadingScreen.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00039] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
>   at Rampastring.XNAUI.WindowManager.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00140] in <fc455ab7275c42ba8bcecc596dc74852>:0 
>   at Microsoft.Xna.Framework.Game+<>c.<.cctor>b__115_1 (Microsoft.Xna.Framework.IUpdateable updateable, Microsoft.Xna.Framework.GameTime gameTime) [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game+SortingFilteringCollection`1[T].ForEachFilteredItem[TUserData] (System.Action`2[T1,T2] action, TUserData userData) [0x0007d] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game.DoUpdate (Microsoft.Xna.Framework.GameTime gameTime) [0x00019] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game.Tick () [0x00122] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle (System.Object sender, System.EventArgs e) [0x00014] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle (System.Int32 grfidlef) [0x0001a] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
>   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop (System.IntPtr dwComponentID, System.Int32 reason, System.Int32 pvLoopData) [0x00243] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
>   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x00282] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
>   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop (System.Int32 reason, System.Windows.Forms.ApplicationContext context) [0x0001a] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
>   at (wrapper remoting-invoke-with-check) System.Windows.Forms.Application+ThreadContext.RunMessageLoop(int,System.Windows.Forms.ApplicationContext)
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.Form mainForm) [0x0000d] in <5ccef4e7d8634b739c09ec3566c7d5be>:0 
>   at MonoGame.Framework.WinFormsGameWindow.RunLoop () [0x00011] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at MonoGame.Framework.WinFormsGamePlatform.RunLoop () [0x00000] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game.Run (Microsoft.Xna.Framework.GameRunBehavior runBehavior) [0x00082] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at Microsoft.Xna.Framework.Game.Run () [0x0000c] in <bde361c85fef4624b5e83e7b4e9406d3>:0 
>   at DTAClient.Startup.Execute () [0x004f0] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
>   at DTAClient.PreStartup.Initialize (DTAClient.StartupParams parameters) [0x0052d] in <514c2045d3fc4ca3b3e62fa86a31b283>:0 
> ```

This has been resolved in the latest client. YR has not migrated to the latest client yet. You can validate this solution in the YR dev channel
