### ISSUE TITLE
Could not find required child control: PlayerOptionsPanel

### ISSUE THREAD

**Issue by 285984303** [CnCNet/xna-cncnet-client#462]
Unhandled exception. System.Collections.Generic.KeyNotFoundException: Could not find required child control: PlayerOptionsPanel
   at ClientGUI.INItializableWindow.FindChild[T](String childName, Boolean optional) in D:\Code\Game\xna-cncnet-client-dev\ClientGUI\INItializableWindow.cs:line 37
   at DTAClient.DXGUI.Multiplayer.GameLobby.GameLobbyBase.Initialize() in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\DXGUI\Multiplayer\GameLobby\GameLobbyBase.cs:line 205
   at DTAClient.DXGUI.Multiplayer.GameLobby.SkirmishLobby.Initialize() in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\DXGUI\Multiplayer\GameLobby\SkirmishLobby.cs:line 34
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChildImmediate(XNAControl child)
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ClientGUI.DarkeningPanel.AddChild(XNAControl child) in D:\Code\Game\xna-cncnet-client-dev\ClientGUI\DarkeningPanel.cs:line 51
   at ClientGUI.DarkeningPanel.AddAndInitializeWithControl(WindowManager wm, XNAControl control) in D:\Code\Game\xna-cncnet-client-dev\ClientGUI\DarkeningPanel.cs:line 107
   at DTAClient.DXGUI.Generic.MainMenu.PostInit() in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\DXGUI\Generic\MainMenu.cs:line 556
   at DTAClient.DXGUI.Generic.LoadingScreen.Finish() in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\DXGUI\Generic\LoadingScreen.cs:line 94
   at DTAClient.DXGUI.Generic.LoadingScreen.Update(GameTime gameTime) in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\DXGUI\Generic\LoadingScreen.cs:line 119
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__116_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at DTAClient.Startup.Execute() in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\Startup.cs:line 136
   at DTAClient.PreStartup.Initialize(StartupParams parameters) in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\PreStartup.cs:line 193
   at DTAClient.Program.Main(String[] args) in D:\Code\Game\xna-cncnet-client-dev\DXMainClient\Program.cs:line 111

C:\Program Files\dotnet\dotnet.exe (进程 1412)已退出，代码为 -532462766。
按任意键关闭此窗口. . .

**Comment by SadPencil** [comment]
https://github.com/CnCNet/xna-cncnet-client/blob/develop/Docs/Migration.md
