### ISSUE TITLE
Connection to GameSurge not working for some 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#481]
**Problem:**

 Some players from the RotE client are experiencing connection issues to GameSurge. They did not have this issue with the client before Net7 changes.

**Client logs supplied from latest client:** 

- [client-develop-2.log](https://github.com/CnCNet/xna-cncnet-client/files/12014608/client-develop-2.log)
- [client-develop.log](https://github.com/CnCNet/xna-cncnet-client/files/12014601/client-develop.log)
the server. Length cannot be less than zero. (Parameter 'length')

**Previous client.log working in cliente before all NET7 changes:**
- [client.log](https://github.com/CnCNet/xna-cncnet-client/files/12014603/client.log)

**Comment by SadPencil** [comment]
This exception is most likely raised by `string.Substring` method in `Connection.cs` file. https://stackoverflow.com/questions/5633661/length-cannot-be-less-than-zero-on-a-blank-line

Need to attach a debugger and observe which command raises the exception.

**Comment by pzhlkj6612** [comment]
> Need to attach a debugger and observe which command raises the exception.

+1.

Printing [stacktrace](https://learn.microsoft.com/dotnet/api/system.exception.stacktrace) might be also helpful:

https://github.com/CnCNet/xna-cncnet-client/blob/a8ed28433d444f40f63c6d99999417079ecebbaf/DXMainClient/Online/Connection.cs#L210

```diff
- Logger.Log("Unable to connect to the server. " + ex.Message);
+ Logger.Log("Unable to connect to the server. " + ex.Message + "\n" + ex.StackTrace);
```

**Comment by Metadorius** [comment]
```
21.07. 15:37:15.632    Unable to connect to the server. Length cannot be less than zero. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
at DTAClient.Online.Connection.HandleMessage(String message) in C:\Users\p\Desktop\CNCNET CLIENT STUFF\xna-cncnet-client\DXMainClient\Online\Connection.cs:line 515
   at DTAClient.Online.Connection.HandleComm() in C:\Users\p\Desktop\CNCNET CLIENT STUFF\xna-cncnet-client\DXMainClient\Online\Connection.cs:line 276
   at DTAClient.Online.Connection.ConnectToServer() in C:\Users\p\Desktop\CNCNET CLIENT STUFF\xna-cncnet-client\DXMainClient\Online\Connection.cs:line 204 
```

**Comment by SadPencil** [comment]
```cs
        private void HandleMessage(string message)
        {
            string msg = overMessage + message;
            overMessage = "";
            while (true)
            {
                int commandEndIndex = msg.IndexOf("\n");
                if (commandEndIndex == -1) whatever;
                else if (msg.Length != commandEndIndex + 1)
                {
                    // throw exception here? so commandEndIndex is 0?
                    string command = msg.Substring(0, commandEndIndex - 1);
```

**Comment by SadPencil** [comment]
Seems like `HandleMessage(message)` would fail when `message` ends up with `"\n"`

**Comment by SadPencil** [comment]
```diff
diff --git a/DXMainClient/Online/Connection.cs b/DXMainClient/Online/Connection.cs
index ba1341ba..f8e8c570 100644
--- a/DXMainClient/Online/Connection.cs
+++ b/DXMainClient/Online/Connection.cs
@@ -499,7 +499,7 @@ namespace DTAClient.Online
         /// <param name="message">The message.</param>
         private void HandleMessage(string message)
         {
-            string msg = overMessage + message;
+            string msg = overMessage + message.Trim();
             overMessage = "";
             while (true)
             {
```
