### ISSUE TITLE
Could not find required child control: PlayerOptionsPanel       Could a pro please provide specific guidance on what to do?

### ISSUE THREAD

**Issue by olengyu** [CnCNet/xna-cncnet-client#503]
15.01. 08:10:41.958    KABOOOOOOM!!! Info:
15.01. 08:10:41.958    Type: System.Collections.Generic.KeyNotFoundException
15.01. 08:10:41.958    Message: Could not find required child control: PlayerOptionsPanel
15.01. 08:10:41.958    Source: ClientGUI
15.01. 08:10:41.958    TargetSite.Name: FindChild
15.01. 08:10:41.970    Stacktrace:    at ClientGUI.INItializableWindow.FindChild[T](String childName, Boolean optional) in E:\xna-cncnet-client\ClientGUI\INItializableWindow.cs:line 37
   at DTAClient.DXGUI.Multiplayer.GameLobby.GameLobbyBase.Initialize() in E:\xna-cncnet-client\DXMainClient\DXGUI\Multiplayer\GameLobby\GameLobbyBase.cs:line 205
   at DTAClient.DXGUI.Multiplayer.GameLobby.SkirmishLobby.Initialize() in E:\xna-cncnet-client\DXMainClient\DXGUI\Multiplayer\GameLobby\SkirmishLobby.cs:line 34
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChildImmediate(XNAControl child)
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ClientGUI.DarkeningPanel.AddChild(XNAControl child) in E:\xna-cncnet-client\ClientGUI\DarkeningPanel.cs:line 51
   at ClientGUI.DarkeningPanel.AddAndInitializeWithControl(WindowManager wm, XNAControl control) in E:\xna-cncnet-client\ClientGUI\DarkeningPanel.cs:line 107
   at DTAClient.DXGUI.Generic.MainMenu.PostInit() in E:\xna-cncnet-client\DXMainClient\DXGUI\Generic\MainMenu.cs:line 556
   at DTAClient.DXGUI.Generic.LoadingScreen.Finish() in E:\xna-cncnet-client\DXMainClient\DXGUI\Generic\LoadingScreen.cs:line 94
   at DTAClient.DXGUI.Generic.LoadingScreen.Update(GameTime gameTime) in E:\xna-cncnet-client\DXMainClient\DXGUI\Generic\LoadingScreen.cs:line 119
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__115_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.Interop.Mso.IMsoComponent.FDoIdle(msoidlef grfidlef)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at DTAClient.Startup.Execute() in E:\xna-cncnet-client\DXMainClient\Startup.cs:line 136
   at DTAClient.PreStartup.Initialize(StartupParams parameters) in E:\xna-cncnet-client\DXMainClient\PreStartup.cs:line 194
   at DTAClient.Program.Main(String[] args) in E:\xna-cncnet-client\DXMainClient\Program.cs:line 111

**Comment by SadPencil** [comment]
This is a place to report software bugs where exceptions/misbehaviors are triggered in steps. From what you've provided, i.e., `KeyNotFoundException`, this is more likely an issue with your own .ini file that invokes an unclaimed constant or something. Refer to [Docs](https://github.com/CnCNet/xna-cncnet-client/tree/develop/Docs) for some documentations and also [cncnet-client-mod-base](https://github.com/Starkku/cncnet-client-mod-base) for examples.

Besides, since this is the first time you ask a question and you speak Chinese, please be advised that phrases like "Could a pro please provide specific guidance on what to do?" (same for "求大神帮助" in Chinese) should be avoided in all circumstances. In a typical Chinese community, newbies tend to use such a phrase to represent their respect -- it is completely not necessary and actually annoying. Neither in a Chinese community or in a global community should you include this phrase. Just ask your question with necessary and precise description.

**Comment by olengyu** [comment]
The problem has been effectively resolved, please close the problem, due to the first use of this community, will pay attention to such problems in the future。

**Comment by olengyu** [comment]
The problem has been effectively resolved, please close the problem。As a newcomer to this community, your advice has enlightened me about the importance of presenting questions clearly and directly in various online settings for better chances of receiving helpful responses. I appreciate your input and will make sure to encapsulate the essence of the problem in my titles moving forward.

**Comment by olengyu** [comment]
The problem has been effectively resolved, please close the problem。As a newcomer to this community, your advice has enlightened me about the importance of presenting questions clearly and directly in various online settings for better chances of receiving helpful responses. I appreciate your input and will make sure to encapsulate the essence of the problem in my titles moving forward.
