### ISSUE TITLE
Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#57]
Log file - haven't seen this one before. 
https://forums.cncnet.org/topic/7325-dta-client-has-stopped-working/
```
10.08. 19:51:13.258    ***Logfile for Yuri's Revenge client***
10.08. 19:51:13.268    Client version: 2.0.6.7
10.08. 19:51:13.268    Loading settings.
10.08. 19:51:13.289    Initializing updater.
10.08. 19:51:13.292    Update mirror count: 1
10.08. 19:51:13.292    Running from: clientdx.exe
10.08. 19:51:13.293    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
10.08. 19:51:13.293    Selected OS profile: WIN7
10.08. 19:51:13.294    Removing partial custom component downloads.
10.08. 19:51:13.295    Checking for the existence of FinalSun.ini.
10.08. 19:51:13.295    FinalSun.ini doesn't exist - writing default settings.
10.08. 19:51:13.295    An exception occured while checking the existence of FinalSun settings
10.08. 19:51:13.296    Writing installation path to the Windows registry.
10.08. 19:51:13.411    Hardware info: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (4 cores)  Video controller: NVIDIA GeForce GT 650M 
10.08. 19:51:13.541    Initializing GameClass.
10.08. 19:51:13.694    InitGraphicsMode: 1920x1200
10.08. 19:51:13.748    Checking local file versions.
10.08. 19:51:13.751    Loading maps.
10.08. 19:51:13.905    Map Maps\Yuri's Revenge\mag doesn't exist!
10.08. 19:51:13.943    Map Maps\Yuri's Revenge\clover doesn't exist!
10.08. 19:51:13.947    Map Maps\Yuri's Revenge\hexbay doesn't exist!
10.08. 19:51:14.068    MapSharer: PREVIEW PATH: Maps\Custom\63897d11c93be002b325e92ea67a307fe2dca227.png
10.08. 19:51:14.073       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:14.081    MapSharer: PREVIEW PATH: Maps\Custom\8297f789f566546c85304cc0a27c1d90825a5786.png
10.08. 19:51:14.084       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:14.085    MapSharer: PREVIEW PATH: Maps\Custom\fc232662b18a7b47256192f11e3a568f9fabff47.png
10.08. 19:51:14.085       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:15.565    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.570    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.575    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.580    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.586    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.591    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.596    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.601    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.606    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.610    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.615    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.710    Attempting to parse INI\Battle.ini to populate mission list.
10.08. 19:51:15.710    File INI\Battle.ini not found. Ignoring.
10.08. 19:51:15.710    Attempting to parse INI\BattleE.ini to populate mission list.
10.08. 19:51:15.710    File INI\BattleE.ini not found. Ignoring.
10.08. 19:51:15.734    Saved Games directory not found!
10.08. 19:51:15.867    Skipping reading statistics because the file doesn't exist!
10.08. 19:51:15.893    KABOOOOOOM!!! Info:
10.08. 19:51:15.893    Message: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
10.08. 19:51:15.894    Source: DTAClient
10.08. 19:51:15.894    TargetSite.Name: .ctor
10.08. 19:51:15.894    Stacktrace:    at ‬​‌⁭‬‎⁬⁮‭‌⁯‌‌‪‫‌​⁪‍​‬‪⁮‫⁭‪‪‪‎‮‏‌‏‮⁮‪‬‭⁯‌‮..ctor()
   at ⁪‭‍‫‎‬‏⁬‪‭‪‬⁭⁪⁮‍⁪‬‬⁪‬⁮⁬‫⁮⁪‮‮​‍‬‪‎⁯​⁫‌‫⁪‬‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ‫⁭⁯⁫⁪⁯​‍‎⁭‪⁮⁮‏‌‏⁪‪‫⁫‌‏⁬‪‍⁯‫‏‪‏​‭‫‫⁪⁫⁭​‬⁯‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ‬‬​‪⁮​‮⁮⁬⁯⁪‌⁮‮​‭⁬​‌⁪⁭‌‍‏⁮‌‬‪‌‫‪‎⁭⁭‫‍‎​‪⁫‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.WindowManager.AddAndInitializeControl(XNAControl control)
   at ⁪⁯⁮‫⁬⁭⁬‫⁭⁭‮‮‬‬‏⁭⁭‏‭⁬⁫⁭‎‬‬⁭⁮⁯‬‪​⁫‭‌⁫‮‬‏​⁮‮.​‏‭⁬⁯⁪‏‌‌‏‪‮​‌‏​⁯‪⁮‮​‍‫‎‬‌‫‪​‎⁮⁮‬‌⁫⁪‌⁫⁪‎‮()
   at ⁪⁯⁮‫⁬⁭⁬‫⁭⁭‮‮‬‬‏⁭⁭‏‭⁬⁫⁭‎‬‬⁭⁮⁯‬‪​⁫‭‌⁫‮‬‏​⁮‮.⁪‮‏​⁬⁬⁮‬‬‫‎‎⁫⁬⁭⁫‬‫⁬​⁪‭‮‍⁫⁭‏‎‮⁯‍⁪‌⁯‎‪‏‭‏‬‮(GameTime )
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ⁪‍⁮⁬⁪⁬⁬⁫‎⁮‏⁬‭⁭‍‏‮⁯‍‏⁪⁭​⁪⁫⁭‫⁯⁮‭‌⁮‭⁭‮‌‪‍‍‫‮.‭⁪‌⁮‏⁫‏‫​⁯‭⁫‎‍⁯​⁪‬⁯‎‌‫‮⁪‪‍‌⁪‍​⁭‌⁬‪‮‭‎⁪​⁮‮()
   at ‎‪‍‬⁪⁮‪‏‪‭‬‌⁬⁪‏⁮⁫⁫‎‫‪⁭‍‍⁭⁪‌​⁮​​⁯‪‭⁬‌⁮‪‭‭‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮(String[] )
   at ‍‎‬⁫‮⁬⁬⁬​‮‌‭‌‮⁪⁭⁭‫‎⁮‎‍⁫‌⁭‎⁫‪‫‬‮‮‎‮‌‍‭⁫​⁮‮.‬⁫⁭⁫⁬‌⁮⁭⁯‮⁮⁯⁮‭⁫​‍⁮⁯⁫‪‮⁬⁫⁪‭‮⁮⁪⁮‫‪⁮⁬⁪‫‬‬⁫⁮‮(String[] )


```

**Comment by Rampastring** [comment]
I remember seeing this twice before. The reason for the error is a corrupted Windows 7 installation that is missing the "Task Bar Communication" object that the client uses for animating the taskbar when downloading updates.

Tell the user to run sfc /scannow from a command prompt with admin privileges.
________________________________
Lähettäjä: Grant Bartlett<mailto:notifications@github.com>
Lähetetty: ‎11.‎8.‎2017 10:28
Vastaanottaja: CnCNet/xna-cncnet-client<mailto:xna-cncnet-client@noreply.github.com>
Kopio: Subscribed<mailto:subscribed@noreply.github.com>
Aihe: [CnCNet/xna-cncnet-client] Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). (#57)


Log file - haven't seen this one before.

10.08. 19:51:13.258    ***Logfile for Yuri's Revenge client***
10.08. 19:51:13.268    Client version: 2.0.6.7
10.08. 19:51:13.268    Loading settings.
10.08. 19:51:13.289    Initializing updater.
10.08. 19:51:13.292    Update mirror count: 1
10.08. 19:51:13.292    Running from: clientdx.exe
10.08. 19:51:13.293    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1
10.08. 19:51:13.293    Selected OS profile: WIN7
10.08. 19:51:13.294    Removing partial custom component downloads.
10.08. 19:51:13.295    Checking for the existence of FinalSun.ini.
10.08. 19:51:13.295    FinalSun.ini doesn't exist - writing default settings.
10.08. 19:51:13.295    An exception occured while checking the existence of FinalSun settings
10.08. 19:51:13.296    Writing installation path to the Windows registry.
10.08. 19:51:13.411    Hardware info: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (4 cores)  Video controller: NVIDIA GeForce GT 650M
10.08. 19:51:13.541    Initializing GameClass.
10.08. 19:51:13.694    InitGraphicsMode: 1920x1200
10.08. 19:51:13.748    Checking local file versions.
10.08. 19:51:13.751    Loading maps.
10.08. 19:51:13.905    Map Maps\Yuri's Revenge\mag doesn't exist!
10.08. 19:51:13.943    Map Maps\Yuri's Revenge\clover doesn't exist!
10.08. 19:51:13.947    Map Maps\Yuri's Revenge\hexbay doesn't exist!
10.08. 19:51:14.068    MapSharer: PREVIEW PATH: Maps\Custom\63897d11c93be002b325e92ea67a307fe2dca227.png
10.08. 19:51:14.073       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:14.081    MapSharer: PREVIEW PATH: Maps\Custom\8297f789f566546c85304cc0a27c1d90825a5786.png
10.08. 19:51:14.084       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:14.085    MapSharer: PREVIEW PATH: Maps\Custom\fc232662b18a7b47256192f11e3a568f9fabff47.png
10.08. 19:51:14.085       at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‎⁮‍⁯‭‮‬‭⁭‪‫‫‏‫‌‪‮‍‭⁯​‌​‮⁭‫⁯‫​‭⁫⁯‌‮‎‌⁭‍‫⁭‮(IniFile , Int32 )
   at ‪⁯‪‪‍⁬⁭‬‫‬⁯‮⁭‎‎⁬⁮⁮⁫⁪⁯⁮‭‏​‫‏‮‏‭‪‪‎⁪‬‮⁮⁪‪⁮‮.‭⁮‏‌‍‭⁯‍​‭‍‬⁭​⁭‬‮‍‍⁮⁭​⁭​‮‮‪‬⁪⁬‪‎⁮⁭⁬‫‭‌‮‍‮()
10.08. 19:51:15.565    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.570    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.575    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.580    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.586    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.591    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.596    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.601    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.606    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.610    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.615    AssetLoader.LoadSound: Sound not found! MainMenu\button.wav
10.08. 19:51:15.710    Attempting to parse INI\Battle.ini to populate mission list.
10.08. 19:51:15.710    File INI\Battle.ini not found. Ignoring.
10.08. 19:51:15.710    Attempting to parse INI\BattleE.ini to populate mission list.
10.08. 19:51:15.710    File INI\BattleE.ini not found. Ignoring.
10.08. 19:51:15.734    Saved Games directory not found!
10.08. 19:51:15.867    Skipping reading statistics because the file doesn't exist!
10.08. 19:51:15.893    KABOOOOOOM!!! Info:
10.08. 19:51:15.893    Message: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
10.08. 19:51:15.894    Source: DTAClient
10.08. 19:51:15.894    TargetSite.Name: .ctor
10.08. 19:51:15.894    Stacktrace:    at ‬​‌⁭‬‎⁬⁮‭‌⁯‌‌‪‫‌​⁪‍​‬‪⁮‫⁭‪‪‪‎‮‏‌‏‮⁮‪‬‭⁯‌‮..ctor()
   at ⁪‭‍‫‎‬‏⁬‪‭‪‬⁭⁪⁮‍⁪‬‬⁪‬⁮⁬‫⁮⁪‮‮​‍‬‪‎⁯​⁫‌‫⁪‬‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ‫⁭⁯⁫⁪⁯​‍‎⁭‪⁮⁮‏‌‏⁪‪‫⁫‌‏⁬‪‍⁯‫‏‪‏​‭‫‫⁪⁫⁭​‬⁯‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.XNAControls.XNAControl.AddChild(XNAControl child)
   at ‬‬​‪⁮​‮⁮⁬⁯⁪‌⁮‮​‭⁬​‌⁪⁭‌‍‏⁮‌‬‪‌‫‪‎⁭⁭‫‍‎​‪⁫‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮()
   at Rampastring.XNAUI.WindowManager.AddAndInitializeControl(XNAControl control)
   at ⁪⁯⁮‫⁬⁭⁬‫⁭⁭‮‮‬‬‏⁭⁭‏‭⁬⁫⁭‎‬‬⁭⁮⁯‬‪​⁫‭‌⁫‮‬‏​⁮‮.​‏‭⁬⁯⁪‏‌‌‏‪‮​‌‏​⁯‪⁮‮​‍‫‎‬‌‫‪​‎⁮⁮‬‌⁫⁪‌⁫⁪‎‮()
   at ⁪⁯⁮‫⁬⁭⁬‫⁭⁭‮‮‬‬‏⁭⁭‏‭⁬⁫⁭‎‬‬⁭⁮⁯‬‪​⁫‭‌⁫‮‬‏​⁮‮.⁪‮‏​⁬⁬⁮‬‬‫‎‎⁫⁬⁭⁫‬‫⁬​⁪‭‮‍⁫⁭‏‎‮⁯‍⁪‌⁯‎‪‏‭‏‬‮(GameTime )
   at Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at ⁪‍⁮⁬⁪⁬⁬⁫‎⁮‏⁬‭⁭‍‏‮⁯‍‏⁪⁭​⁪⁫⁭‫⁯⁮‭‌⁮‭⁭‮‌‪‍‍‫‮.‭⁪‌⁮‏⁫‏‫​⁯‭⁫‎‍⁯​⁪‬⁯‎‌‫‮⁪‪‍‌⁪‍​⁭‌⁬‪‮‭‎⁪​⁮‮()
   at ‎‪‍‬⁪⁮‪‏‪‭‬‌⁬⁪‏⁮⁫⁫‎‫‪⁭‍‍⁭⁪‌​⁮​​⁯‪‭⁬‌⁮‪‭‭‮.‍‪⁫⁭⁯​‪‎⁭‫‎⁫‮‫‫⁬​⁬‫‍‪⁭‭‮‬‎⁬‎⁬‏‭⁬‎​⁭​⁭‮⁪‍‮(String[] )
   at ‍‎‬⁫‮⁬⁬⁬​‮‌‭‌‮⁪⁭⁭‫‎⁮‎‍⁫‌⁭‎⁫‪‫‬‮‮‎‮‌‍‭⁫​⁮‮.‬⁫⁭⁫⁬‌⁮⁭⁯‮⁮⁯⁮‭⁫​‍⁮⁯⁫‪‮⁬⁫⁪‭‮⁮⁪⁮‫‪⁮⁬⁪‫‬‬⁫⁮‮(String[] )

**Comment by GrantBartlett** [comment]
Thanks that seems to point to the issue. Closed for now.
